name = "PairPlots"
uuid = "43a3c2be-4208-490b-832a-a21dcd55d7da"
authors = ["William Thompson <wthompson@uvic.ca>"]
version = "2.3.1"

[deps]
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TableOperations = "ab02a1b2-a7df-11e8-156e-fb1833f50b87"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
MCMCChainsExt = "MCMCChains"
PairPlotsDynamicQuantitiesExt = "DynamicQuantities"
PairPlotsDynamicUnitfulExt = "Unitful"

[compat]
Contour = "0.6"
Distributions = "0.25"
KernelDensity = "0.6"
LinearAlgebra = "1"
MCMCChains = "5.0, 6.0"
Makie = "0.20"
Measures = "0.3.1"
Missings = "1"
NamedTupleTools = "0.14"
OrderedCollections = "1.4"
PolygonOps = "0.1.1"
PrecompileTools = "1.0"
Printf = "1"
RecipesBase = "1"
Requires = "1"
StaticArrays = "1.0.0"
Statistics = "1"
StatsBase = "0.32 - 0.33, 0.34"
TableOperations = "1"
Tables = "1.4.1"
julia = "1.7.0"

[extras]
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
